haproxy:
  image: haproxy:1.5
  ports:
   - "1936:1936"
   - "80:80"
   - "5000:5000"
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  links:
   - flask
flask:
  image: full-gamut
  volumes:
   - ./flask/app.py:/src/app.py
  links:
   - mariadb
mariadb:
  image: mariadb
  ports:
   - "3306:3306"
  environment:
   - MYSQL_DATABASE=api
   - MYSQL_USER=root
   - MYSQL_ROOT_PASSWORD=Password123
   - TERM=dumb
  volumes:
   - ./mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
#   - /var/container-data/gamut:/var/lib/mysql:rw
